### PR TITLE
Add missing  ¯\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by pxlpnk**

### CODE REVIEW

**Comment by dkhamsing** [comment]
dope pr

**Comment by skade** [comment]
How did I not merge this? Well... ¯_(ツ)_/¯

**Comment by pxlpnk** [comment]
Can be restored if wanted. I didn't want to be too pushy.

**Comment by skade** [comment]
I think I'm good. Keeps the burden of maintenance away from me.

**Pull request closed without merging**
